name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  gh_pages: 
    runs-on: ubuntu-latest
    steps:
      -
        name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
