name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public

